==> Uploading build...
==> Uploaded in 5.6s. Compression took 2.5s
==> Build successful ðŸŽ‰
==> Deploying...
==> Running 'gunicorn --bind 0.0.0.0:$PORT main:app'
DEBUG:sentry_sdk.errors:[Tracing] Create new propagation context: {'trace_id': '1bd91c1528b24305a317c5089bff928f', 'span_id': '8a0e267c27ec981b', 'parent_span_id': None, 'dynamic_sampling_context': None}
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run
    super().run()
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 57, in __init__
    self.setup(app)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 117, in setup
    self.app.wsgi()
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): o1129642.ingest.us.sentry.io:443
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/render/project/src/main.py", line 4, in <module>
    from app import app
  File "/opt/render/project/src/app.py", line 72, in <module>
    from models import User, Paste
  File "/opt/render/project/src/models.py", line 12, in <module>
    class User(UserMixin, db.Model):
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask_sqlalchemy/model.py", line 100, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask_sqlalchemy/model.py", line 120, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 520, in __init__
    super().__init__(registry, cls_, mapper_kw)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 344, in __init__
    instrumentation.register_class(
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/instrumentation.py", line 684, in register_class
    manager._update_state(
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/instrumentation.py", line 209, in _update_state
    registry._add_manager(self)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 1380, in _add_manager
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Class '<class 'models.User'>' already has a primary mapper defined. 
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
DEBUG:urllib3.connectionpool:https://o1129642.ingest.us.sentry.io:443 "POST /api/4509130694787072/store/ HTTP/1.1" 200 0
==> Exited with status 1
==> Common ways to troubleshoot your deploy: https://render.com/docs/troubleshooting-deploys
==> Running 'gunicorn --bind 0.0.0.0:$PORT main:app'
DEBUG:sentry_sdk.errors:[Tracing] Create new propagation context: {'trace_id': '0d2df77d6d874503b1cbe1920d80f685', 'span_id': '9f3382ed1a1c972c', 'parent_span_id': None, 'dynamic_sampling_context': None}
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run
    super().run()
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 57, in __init__
    self.setup(app)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 117, in setup
    self.app.wsgi()
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/render/project/src/main.py", line 4, in <module>
    from app import app
  File "/opt/render/project/src/app.py", line 72, in <module>
    from models import User, Paste
  File "/opt/render/project/src/models.py", line 12, in <module>
    class User(UserMixin, db.Model):
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask_sqlalchemy/model.py", line 100, in __init__
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): o1129642.ingest.us.sentry.io:443
    super().__init__(name, bases, d, **kwargs)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask_sqlalchemy/model.py", line 120, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 520, in __init__
    super().__init__(registry, cls_, mapper_kw)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 344, in __init__
    instrumentation.register_class(
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/instrumentation.py", line 684, in register_class
    manager._update_state(
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/instrumentation.py", line 209, in _update_state
    registry._add_manager(self)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 1380, in _add_manager
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Class '<class 'models.User'>' already has a primary mapper defined. 
DEBUG:urllib3.connectionpool:https://o1129642.ingest.us.sentry.io:443 "POST /api/4509130694787072/store/ HTTP/1.1" 200 0